name: Build Worker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'worker/**'
      - '.github/workflows/call-docker-build-worker.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'worker/**'
      - '.github/workflows/call-docker-build-worker.yaml'

jobs:
  call-docker-build:

    name: Worker Call Docker Build

    uses: dockersamples/.github/.github/workflows/reusable-docker-build.yaml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write
    
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      dockerhub-enable: true
      ghcr-enable: true
      image-names: |
        ghcr.io/dockersamples/example-voting-app-worker
        dockersamples/examplevotingapp_worker
      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr

      context: worker
      
      platforms: linux/amd64,linux/arm64,linux/arm/v7

      if: github.event_name == 'push' && github.ref == 'refs/heads/main'